version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: socket.io
    versions:
    - 2.4.0
    - 4.0.0
  - dependency-name: express-rate-limit
    versions:
    - 5.2.6
