blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://discourse.isledocs.com/
    about: Please ask and answer questions on how to use ISLE on the community forum.
  - name: Documentation
    url: https://isledocs.com/
    about: Please consult the official documentation to see whether a usage question of yours has already been answered there
